### ISSUE TITLE
ws-butler-global-exempt-modes doesn't quite work

### ISSUE THREAD

**Issue by dabrahams** [lewang/ws-butler#48]
If I want to exempt a mode, I have to exempt a mode it's derived from.  Will submit a PR

**Comment by phil-s** [comment]
What's an example of the problem?

If `(memq major-mode ws-butler-global-exempt-modes)` then it's also true that `(apply #'derived-mode-p ws-butler-global-exempt-modes)` so this PR looks like a no-op to me.

**Comment by dabrahams** [comment]
Afraid I don't remember, and if what you say is true I was probably simply dead wrong :-)
Thanks, I'll close it for you.
